/**
* @file main.cpp 
* @author Andres Sevillano 
* @date June 2018
* @brief Silly process to check it out ideas before writing down proper unit tests.
*
* Pay attention to the fact that some external defined constant for the  version number is used. 
* 
* @see https://github.com/xue2sheng/SoftwareChallenge/blob/master/README.md
*/

#include "main.hpp"

using namespace std;
using namespace SoftwareChallenge;

int main()
{
	/** Generated by CMake in order to have the very same version number for binaries and for doxygen documentation */
	extern const char* SOFTWARE_CHALLENGE_VERSION;
	cout << SOFTWARE_CHALLENGE_VERSION << endl << endl;

	Collection collection;
	collection.add("John", "Ian");
	collection.add("John", "Earl");
	
	for (const auto& i : collection) {
		cout << i.first.c_str() << " index=" << i.second.index << " size=" << i.second.size() << endl;
		for (const auto& j : i.second) {
			cout << "  friend=" << j << endl;
		}
	}

	/*
	Collection network;
	network.process("C:/Users/user/Code/SoftwareChallenge/data/test01.txt");
	for (const auto& i : network) {
		cout << i.first.c_str() << " -> " << i.second.index << endl;
	}
	cout << endl << "size()=" << network.size() << endl << endl;
	*/

	return 0;
}
